# apps/participacao/urls.py
from django.urls import path
from .views import (
    login,
    logout_view,
    index,
    participacao,
    editar_dias_trabalhados,
    recalcular_participacao,
    configurar_participacao_setor,
    configurar_regras_participacao,
    configurar_setores_participacao,
    cadastrar_setor,
    cadastrar_funcionario,
    funcionarios,
    editar_funcionario,
    alternar_abono,
    inserir_eventos,
    listar_eventos,
    importar_planilha_participacao,
    configurar_proporcional,
    configurar_ajustes_participacao,
    calcular_participacao,
    revogar_aprovacao_participacao,
    recalcular_funcionario,
    adicionar_advertencia,
    aprovar_participacao,
    detalhes_calculo_participacao,
    gerar_relatorio_pdf,
    gerar_relatorio_excel,
    download_extrato_pdf,
    download_relatorio_pagamento,
    extrato,
    logs_geral,
    logs,
    configurar_abono_funcionario
)

app_name = 'Participacao'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout_view, name='logout'),
    path('', index, name='index'),
    path('participacao/', participacao, name='participacao'),
    path('editar_dias_trabalhados/<int:participacao_id>/', editar_dias_trabalhados, name='editar_dias_trabalhados'),
    path('recalcular_participacao/', recalcular_participacao, name='recalcular_participacao'),
    path('configurar_participacao_setor/', configurar_participacao_setor, name='configurar_participacao_setor'),
    path('configurar_regras_participacao/', configurar_regras_participacao, name='configurar_regras_participacao'),
    path('configurar_setores_participacao/', configurar_setores_participacao, name='configurar_setores_participacao'),
    path('cadastrar_setor/', cadastrar_setor, name='cadastrar_setor'),
    path('cadastrar_funcionario/', cadastrar_funcionario, name='cadastrar_funcionario'),
    path('funcionarios/', funcionarios, name='funcionarios'),
    path('editar_funcionario/<int:funcionario_id>/', editar_funcionario, name='editar_funcionario'),
    path('alternar_abono/', alternar_abono, name='alternar_abono'),
    path('inserir_eventos/', inserir_eventos, name='inserir_eventos'),
    path('listar_eventos/<int:funcionario_id>/', listar_eventos, name='listar_eventos'),
    path('importar_planilha_participacao/', importar_planilha_participacao, name='importar_planilha_participacao'),
    path('configurar_proporcional/', configurar_proporcional, name='configurar_proporcional'),
    path('configurar_ajustes_participacao/', configurar_ajustes_participacao, name='configurar_ajustes_participacao'),
    path('calcular_participacao/', calcular_participacao, name='calcular_participacao'),
    path('revogar_aprovacao_participacao/', revogar_aprovacao_participacao, name='revogar_aprovacao_participacao'),
    path('recalcular_funcionario/<int:funcionario_id>/', recalcular_funcionario, name='recalcular_funcionario'),
    path('adicionar_advertencia/', adicionar_advertencia, name='adicionar_advertencia'),
    path('aprovar_participacao/', aprovar_participacao, name='aprovar_participacao'),
    path('detalhes_calculo_participacao/', detalhes_calculo_participacao, name='detalhes_calculo_participacao'),
    path('gerar_relatorio_pdf/', gerar_relatorio_pdf, name='gerar_relatorio_pdf'),
    path('gerar_relatorio_excel/', gerar_relatorio_excel, name='gerar_relatorio_excel'),
    path('download_extrato_pdf/<str:funcionario_nome>/', download_extrato_pdf, name='download_extrato_pdf'),
    path('download_relatorio_pagamento/', download_relatorio_pagamento, name='download_relatorio_pagamento'),
    path('extrato/<str:funcionario>/', extrato, name='extrato'),
    path('logs_geral/', logs_geral, name='logs_geral'),
    path('logs/<int:funcionario_id>/', logs, name='logs'),
    path('configurar_abono_funcionario/', configurar_abono_funcionario, name='configurar_abono_funcionario'),
]