# Generated by Django 5.2 on 2025-06-12 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraParticipacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador', models.CharField(max_length=50, unique=True, verbose_name='Indicador')),
                ('periodo', models.CharField(choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral')], default='mensal', max_length=10, verbose_name='Período')),
                ('tolerancia', models.IntegerField(default=0, verbose_name='Tolerância')),
                ('representatividade', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Representatividade (%)')),
                ('valor_subsequente', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Valor Subsequente (%)')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
            ],
            options={
                'verbose_name': 'Regra de Participação',
                'verbose_name_plural': 'Regras de Participação',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Setor')),
                ('valor_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Base')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('recebe_participacao', models.BooleanField(default=False, verbose_name='Recebe Participação')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.CreateModel(
            name='ValoresParticipacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(max_length=10, unique=True, verbose_name='Trimestre')),
                ('documentos_normais', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Documentos Normais')),
                ('documentos_diferenciados', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Documentos Diferenciados')),
                ('deducao_normal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Dedução Normal')),
                ('deducao_diferenciada', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Dedução Diferenciada')),
                ('percentual_normal', models.DecimalField(decimal_places=2, default=40.0, max_digits=5, verbose_name='Percentual Normal (%)')),
                ('percentual_diferenciada', models.DecimalField(decimal_places=2, default=30.0, max_digits=5, verbose_name='Percentual Diferenciado (%)')),
                ('percentual_faturamento', models.DecimalField(decimal_places=2, default=55.0, max_digits=5, verbose_name='Percentual Faturamento (%)')),
                ('percentual_demais', models.DecimalField(decimal_places=2, default=45.0, max_digits=5, verbose_name='Percentual Demais (%)')),
            ],
            options={
                'verbose_name': 'Valor de Participação',
                'verbose_name_plural': 'Valores de Participação',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('data_admissao', models.DateField(blank=True, null=True, verbose_name='Data de Admissão')),
                ('data_demissao', models.DateField(blank=True, null=True, verbose_name='Data de Demissão')),
                ('tipo_acesso', models.CharField(choices=[('gestor', 'Gestor'), ('master_admin', 'Master Admin')], default='gestor', max_length=20, verbose_name='Tipo de Acesso')),
                ('tipo_participacao', models.CharField(choices=[('normal', 'Normal'), ('proporcional', 'Proporcional'), ('menor_aprendiz', 'Menor Aprendiz')], default='normal', max_length=20, verbose_name='Tipo de Participação')),
                ('percentual_participacao', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='Percentual de Participação (%)')),
                ('proporcional', models.IntegerField(default=0, verbose_name='Dias Proporcionais')),
                ('trimestre_inicio_participacao', models.CharField(blank=True, max_length=10, null=True, verbose_name='Trimestre de Início')),
                ('abono_ativo', models.BooleanField(default=False, verbose_name='Abono Ativo')),
                ('abono_valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do Abono')),
                ('abono_type', models.CharField(choices=[('fixed', 'Fixo'), ('percentage', 'Percentual')], default='fixed', max_length=10, verbose_name='Tipo de Abono')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participacao.setor', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do Evento')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de Evento')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participacao.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_attempted', models.CharField(max_length=150, verbose_name='Usuário Tentado')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('is_malicious', models.BooleanField(default=False, verbose_name='Tentativa Maliciosa')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Autenticado')),
            ],
            options={
                'verbose_name': 'Tentativa de Login',
                'verbose_name_plural': 'Tentativas de Login',
            },
        ),
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(max_length=10, verbose_name='Trimestre')),
                ('dias_trabalhados', models.IntegerField(default=0, verbose_name='Dias Trabalhados')),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Bruto')),
                ('final_participacao', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Final')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participacao.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Participação',
                'verbose_name_plural': 'Participações',
            },
        ),
        migrations.CreateModel(
            name='AprovacaoSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(max_length=10, verbose_name='Trimestre')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('pago', 'Pago')], default='pendente', max_length=20, verbose_name='Status')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participacao.setor', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Aprovação de Setor',
                'verbose_name_plural': 'Aprovações de Setores',
            },
        ),
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Ação')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Ação do Usuário',
                'verbose_name_plural': 'Logs de Ações do Usuário',
            },
        ),
    ]
